DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS USER_MESSAGE;
DROP TABLE IF EXISTS CONTACT;

CREATE TABLE USER (
  uid INT PRIMARY KEY,
  username VARCHAR(500) NOT NULL,
  password VARCHAR(500) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  avatar VARCHAR(500) NOT NULL
);

CREATE TABLE MESSAGE (
  mid INT AUTO_INCREMENT  PRIMARY KEY,
  content VARCHAR(1000) NOT NULL,
  sender_id INT NOT NULL,
  recipient_id INT NOT NULL,
  msg_type INT NOT NULL,
  create_time TIMESTAMP NOT NUll
);

CREATE TABLE USER_MESSAGE (
  owner_uid INT NOT NULL,
  other_uid INT NOT NULL,
  mid INT NOT NULL,
  type INT NOT NULL,
  create_time TIMESTAMP NOT NULL,
  PRIMARY KEY (`owner_uid`,`mid`)
);
CREATE INDEX `idx_owneruid_otheruid_msgid` ON USER_MESSAGE(`owner_uid`,`other_uid`,`mid`);

CREATE TABLE CONTACT (
  owner_uid INT NOT NULL,
  other_uid INT NOT NULL,
  mid INT NOT NULL,
  type INT NOT NULL,
  create_time TIMESTAMP NOT NULL,
  PRIMARY KEY (`owner_uid`,`other_uid`)
);